SELECT * FROM RHU.Replication_Config;
/
SELECT * FROM RHU.Replication_Detail order by ID_RD desc;
--DELETE FROM RHU.Replication_Detail WHERE DOCUMENT_NUMBER=485696323;
/
SELECT *
FROM QUEUE_SEL_MASIVO;
/
SELECT *
FROM QUEUE_SEL_REPLICATION
/
--****************************************************************
--** CREATE OR REPLACE TRIGGER PAR.HV_RESTRICCIONES_AUDIT
--** AFTER INSERT OR UPDATE ON PAR.HOJA_VIDA_RESTRICCIONES
--****************************************************************
SELECT * FROM PAR.HOJA_VIDA_RESTRICCIONES ORDER BY REST_FECHA_GRABA DESC;
/
INSERT INTO PAR.HOJA_VIDA_RESTRICCIONES (DCM_RADICACION,REST_ITEM,REST_TIPO,REST_MOTIVO,REST_USUARIO_GRABA,REST_FECHA_GRABA,TDC_TD,EMP_ND,TDC_TD_EPL,EPL_ND
,CAU_SECUENCIA,TDC_TD_ORG,EMP_ND_ORG,REST_VALOR,REST_FECHA_VIGENCIA,REST_MOTIVO_CLIENTE,PRR_CODIGO) 
VALUES ('1069760782','1','RESTRICTIVO','LE CAIGO MAL AL JEFE','S_DEYCI',TO_DATE('14/03/07','DD/MM/RR'),NULL,NULL,'CC','1069760782','3',NULL,NULL,NULL,NULL,NULL,NULL);
/
SELECT * FROM PAR.HOJA_VIDA_RESTRICCIONES WHERE EPL_ND='1069760782';
/
DELETE FROM PAR.HOJA_VIDA_RESTRICCIONES WHERE EPL_ND='1069760782';
/
--****************************************************************
--** CREATE OR REPLACE TRIGGER PAR.HV_REQUISICION_AUDIT
--** AFTER INSERT OR UPDATE ON PAR.REQUISICION_HOJA_VIDA
--****************************************************************
SELECT * FROM PAR.REQUISICION_HOJA_VIDA ORDER BY REQ_CONSECUTIVO DESC;
/
SELECT *
FROM PAR.REQUISICION_HOJA_VIDA
WHERE RQHV_FECHA BETWEEN SYSDATE - 7 AND SYSDATE
ORDER BY RQHV_FECHA DESC;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='DISPONIBLE' WHERE REQ_CONSECUTIVO=343637 AND DCM_RADICACION=4223023;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='APLICADO' WHERE REQ_CONSECUTIVO=343637 AND DCM_RADICACION=4223023;
/
--****************************************************************
--** CREATE OR REPLACE TRIGGER RHU.HV_CONTRATO_AUDIT
--** AFTER INSERT OR UPDATE ON RHU.CONTRATO
--****************************************************************
SELECT * FROM RHU.CONTRATO ORDER BY CTO_NUMERO DESC;
/
SELECT *
FROM RHU.CONTRATO
WHERE CTO_FECING BETWEEN SYSDATE - 7 AND SYSDATE
ORDER BY CTO_FECING DESC;
/
UPDATE RHU.CONTRATO SET ECT_SIGLA='INA' WHERE EPL_ND=1031806008 AND CTO_NUMERO=1666265;
/
UPDATE RHU.CONTRATO SET ECT_SIGLA='PRE' WHERE EPL_ND=1031806008 AND CTO_NUMERO=1666265;
/
UPDATE RHU.CONTRATO SET ECT_SIGLA='ACT' WHERE EPL_ND=1031806008 AND CTO_NUMERO=1666265;

/
--****************************************************************
--** CREATE OR REPLACE TRIGGER PAR.REQ_OKVAL_DOCS_REPLICATE
--** AFTER INSERT OR UPDATE ON PAR.REQUISICION_HOJA_VIDA
--****************************************************************
SELECT * FROM RHU.OBSERVACION_LINGRESO ORDER BY LIB_CONSECUTIVO DESC;
/
SELECT *
FROM PAR.REQUISICION_HOJA_VIDA
WHERE RQHV_FECHA BETWEEN SYSDATE - 7 AND SYSDATE
ORDER BY RQHV_FECHA DESC;
/
SELECT * FROM RHU.REQUIRED_DOCUMENTS;
/
SELECT *
FROM perfil_estado_lingreso pel, perfil_detalle_lingreso pdl
WHERE pel.pre_codigo = pdl.pre_codigo
AND pel.lib_estado = pdl.lib_estado
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='DISPONIBLE' WHERE REQ_CONSECUTIVO=343692 AND DCM_RADICACION=4223102;--CC 5489623565
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='CONFIR_OK' WHERE REQ_CONSECUTIVO=343692 AND DCM_RADICACION=4223102;--CC 5489623565
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='ASISTIO' WHERE REQ_CONSECUTIVO=343692 AND DCM_RADICACION=4223102;--CC 5489623565
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='OK_VALIDADO' WHERE REQ_CONSECUTIVO=343692 AND DCM_RADICACION=4223102;--CC 5489623565
/
--****************************************************************
--** CREATE OR REPLACE TRIGGER RHU.HV_EMPLEADO_REPL
--** AFTER INSERT OR UPDATE ON RHU.EMPLEADO
--****************************************************************
/
--****************************************************************
--** CREATE OR REPLACE TRIGGER RHU.HV_EMPLEADO_MASV
--** AFTER INSERT OR UPDATE ON RHU.EMPLEADO
--****************************************************************
/
SELECT * FROM EMPLEADO  ORDER BY AUD_FECHA DESC;
/
SELECT *
FROM EMPLEADO
WHERE AUD_FECHA BETWEEN SYSDATE - 7 AND SYSDATE
ORDER BY AUD_FECHA DESC;
/
UPDATE EMPLEADO SET FUENTE='CONTRATO' WHERE EPL_ND=485696323 AND TDC_TD='CC';
/
UPDATE EMPLEADO SET FUENTE='COMPUTRABAJO_MASIVO' WHERE EPL_ND=485696323 AND TDC_TD='CC';

/
SELECT * FROM RHU.Replication_Config WHERE LOCAL_TABLE_REF = 'RHU.EMPLEADO' AND GCP_TABLE_REF = 'BasicData'
