SELECT * FROM RHU.Replication_Config;
/
SELECT * FROM RHU.Replication_Detail order by ID_RD desc;
--DELETE FROM RHU.Replication_Detail WHERE DOCUMENT_NUMBER=485696323;
/
SELECT * FROM USUARIO where LOGIN_USUARIO ='keimartinez';
/
SELECT *
FROM QUEUE_SEL_MASIVO;
/
SELECT *
FROM QUEUE_SEL_REPLICATION;
/
--****************************************************************
--** CREATE OR REPLACE TRIGGER PAR.HV_RESTRICCIONES_AUDIT
--** AFTER INSERT OR UPDATE ON PAR.HOJA_VIDA_RESTRICCIONES
--****************************************************************
SELECT * FROM PAR.HOJA_VIDA_RESTRICCIONES ORDER BY REST_FECHA_GRABA DESC;
/

/
<<<<<<< HEAD
SELECT * FROM PAR.HOJA_VIDA_RESTRICCIONES WHERE EPL_ND='1255083';
/
SELECT ID_RD, DATA_JSON, STATE_RD, DATE_RD
FROM RHU.REPLICATION_DETAIL
WHERE DOCUMENT_NUMBER = '1255083'
ORDER BY DATE_RD DESC;
/
GRANT SELECT ON RHU.TRIGGER_DEBUG_LOG TO PUBLIC;
/
CREATE TABLE RHU.TRIGGER_DEBUG_LOG (
    FECHA    DATE,
    CAU_SEQ  NUMBER,
    CAU_DESC VARCHAR2(100),
    IT_BLOCK VARCHAR2(10),
    USUARIO  VARCHAR2(30)
);

/
DELETE FROM PAR.HOJA_VIDA_RESTRICCIONES WHERE EPL_ND='1255083';
/
INSERT INTO PAR.HOJA_VIDA_RESTRICCIONES (--cDcY1RxLVSDOf6nuwN7NkqM2qsxU GCP
    DCM_RADICACION,
    REST_ITEM,
    REST_TIPO,
    REST_MOTIVO,
    REST_USUARIO_GRABA,
    REST_FECHA_GRABA,
    TDC_TD,
    EMP_ND,
    TDC_TD_EPL,
    EPL_ND,
    CAU_SECUENCIA,
    TDC_TD_ORG,
    EMP_ND_ORG,
    REST_VALOR,
    REST_FECHA_VIGENCIA,
    REST_MOTIVO_CLIENTE,
    PRR_CODIGO
)
VALUES (
    (
        SELECT DCM_RADICACION
        FROM (
            SELECT DCM_RADICACION
            FROM PAR.HOJA_VIDA_RESTRICCIONES
            WHERE DCM_RADICACION IS NOT NULL
            ORDER BY REST_FECHA_GRABA DESC
        )
        WHERE ROWNUM = 1
    ),
    '1',
    'RESTRICTIVO',
    'EXTRABAJADOR Prueba JSFS',
    'S_DEYCI',
    TO_DATE(SYSDATE),
    NULL,
    NULL,
    'CC',
    '1255083',
    '1',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
);
/
SELECT CAU_SECUENCIA, CAU_DESCRIPCION
FROM RHU.CAUSAL
WHERE CAU_SECUENCIA = 1;

/
=======
SELECT * FROM PAR.HOJA_VIDA_RESTRICCIONES WHERE EPL_ND='1075875006';
/
DELETE FROM PAR.HOJA_VIDA_RESTRICCIONES WHERE EPL_ND='1075875006';

>>>>>>> 881ac0ffe60537651b3bd138deb24aa2e246d04d
INSERT INTO PAR.HOJA_VIDA_RESTRICCIONES (DCM_RADICACION,REST_ITEM,REST_TIPO,REST_MOTIVO,REST_USUARIO_GRABA,REST_FECHA_GRABA,TDC_TD,EMP_ND,TDC_TD_EPL,EPL_ND
,CAU_SECUENCIA,TDC_TD_ORG,EMP_ND_ORG,REST_VALOR,REST_FECHA_VIGENCIA,REST_MOTIVO_CLIENTE,PRR_CODIGO) 
VALUES ('1075875006','1','RESTRICTIVO','LE CAIGO MAL AL JEFE deiby Armando','S_DEYCI',TO_DATE('14/03/07','DD/MM/RR'),NULL,NULL,'CC','1075875006','3',NULL,NULL,NULL,NULL,NULL,NULL);
/
INSERT INTO PAR.HOJA_VIDA_RESTRICCIONES (DCM_RADICACION,REST_ITEM,REST_TIPO,REST_MOTIVO,REST_USUARIO_GRABA,REST_FECHA_GRABA,TDC_TD,EMP_ND,TDC_TD_EPL,EPL_ND
,CAU_SECUENCIA,TDC_TD_ORG,EMP_ND_ORG,REST_VALOR,REST_FECHA_VIGENCIA,REST_MOTIVO_CLIENTE,PRR_CODIGO) 
VALUES ('556332','1','RESTRICTIVO','LE CAIGO MAL AL JEFE CRISTIAN','S_DEYCI',TO_DATE('14/03/07','DD/MM/RR'),NULL,NULL,'CC','556332','3',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO PAR.HOJA_VIDA_RESTRICCIONES (DCM_RADICACION,REST_ITEM,REST_TIPO,REST_MOTIVO,REST_USUARIO_GRABA,REST_FECHA_GRABA,TDC_TD,EMP_ND,TDC_TD_EPL,EPL_ND
,CAU_SECUENCIA,TDC_TD_ORG,EMP_ND_ORG,REST_VALOR,REST_FECHA_VIGENCIA,REST_MOTIVO_CLIENTE,PRR_CODIGO) 
VALUES ('321837','1','RESTRICTIVO','LE CAIGO MAL AL JEFE CRISTIAN','S_DEYCI',TO_DATE('14/03/07','DD/MM/RR'),NULL,NULL,'CC','321837','3',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO PAR.HOJA_VIDA_RESTRICCIONES (DCM_RADICACION,REST_ITEM,REST_TIPO,REST_MOTIVO,REST_USUARIO_GRABA,REST_FECHA_GRABA,TDC_TD,EMP_ND,TDC_TD_EPL,EPL_ND
,CAU_SECUENCIA,TDC_TD_ORG,EMP_ND_ORG,REST_VALOR,REST_FECHA_VIGENCIA,REST_MOTIVO_CLIENTE,PRR_CODIGO) 
VALUES ('324656','1','RESTRICTIVO','LE CAIGO MAL AL JEFE CRISTIAN','S_DEYCI',TO_DATE('14/03/07','DD/MM/RR'),NULL,NULL,'CC','324656','3',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO PAR.HOJA_VIDA_RESTRICCIONES (DCM_RADICACION,REST_ITEM,REST_TIPO,REST_MOTIVO,REST_USUARIO_GRABA,REST_FECHA_GRABA,TDC_TD,EMP_ND,TDC_TD_EPL,EPL_ND
,CAU_SECUENCIA,TDC_TD_ORG,EMP_ND_ORG,REST_VALOR,REST_FECHA_VIGENCIA,REST_MOTIVO_CLIENTE,PRR_CODIGO) 
VALUES ('1032796','1','RESTRICTIVO','LE CAIGO MAL AL JEFE CRISTIAN','S_DEYCI',TO_DATE('14/03/07','DD/MM/RR'),NULL,NULL,'CC','1032796','3',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO PAR.HOJA_VIDA_RESTRICCIONES (DCM_RADICACION,REST_ITEM,REST_TIPO,REST_MOTIVO,REST_USUARIO_GRABA,REST_FECHA_GRABA,TDC_TD,EMP_ND,TDC_TD_EPL,EPL_ND
,CAU_SECUENCIA,TDC_TD_ORG,EMP_ND_ORG,REST_VALOR,REST_FECHA_VIGENCIA,REST_MOTIVO_CLIENTE,PRR_CODIGO) 
VALUES ('208547','1','RESTRICTIVO','LE CAIGO MAL AL JEFE CRISTIAN','S_DEYCI',TO_DATE('14/03/07','DD/MM/RR'),NULL,NULL,'CC','208547','3',NULL,NULL,NULL,NULL,NULL,NULL);
/
DELETE FROM PAR.HOJA_VIDA_RESTRICCIONES 
WHERE DCM_RADICACION = '556332' AND REST_ITEM = '1' AND EPL_ND = '556332';

DELETE FROM PAR.HOJA_VIDA_RESTRICCIONES 
WHERE DCM_RADICACION = '321837' AND REST_ITEM = '1' AND EPL_ND = '321837';

DELETE FROM PAR.HOJA_VIDA_RESTRICCIONES 
WHERE DCM_RADICACION = '324656' AND REST_ITEM = '1' AND EPL_ND = '324656';

DELETE FROM PAR.HOJA_VIDA_RESTRICCIONES 
WHERE DCM_RADICACION = '1032796' AND REST_ITEM = '1' AND EPL_ND = '1032796';

DELETE FROM PAR.HOJA_VIDA_RESTRICCIONES 
WHERE DCM_RADICACION = '208547' AND REST_ITEM = '1' AND EPL_ND = '208547';

/
--****************************************************************
--** CREATE OR REPLACE TRIGGER PAR.HV_REQUISICION_AUDIT
--** AFTER INSERT OR UPDATE ON PAR.REQUISICION_HOJA_VIDA
--****************************************************************
SELECT * FROM PAR.REQUISICION_HOJA_VIDA WHERE EPL_ND=1053585200 ;
/
SELECT STDO_ESTADO
FROM PAR.REQUISICION_HOJA_VIDA
GROUP BY (STDO_ESTADO);
/
SELECT * FROM RHU.Replication_Detail order by ID_RD desc;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='DISPONIBLE'WHERE REQ_CONSECUTIVO=351376 AND DCM_RADICACION=4330818;
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='CONFIR_OK'WHERE REQ_CONSECUTIVO=351376 AND DCM_RADICACION=4330818;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='DISPONIBLE', RQHV_CEDULA=321837 WHERE REQ_CONSECUTIVO=268784 AND DCM_RADICACION=4330998;
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='CONFIR_OK', RQHV_CEDULA=321837 WHERE REQ_CONSECUTIVO=268784 AND DCM_RADICACION=4330998;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='DISPONIBLE', RQHV_CEDULA=324656 WHERE REQ_CONSECUTIVO=351376 AND DCM_RADICACION=4330753;
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='CONFIR_OK', RQHV_CEDULA=324656 WHERE REQ_CONSECUTIVO=351376 AND DCM_RADICACION=4330753;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='DISPONIBLE', RQHV_CEDULA=1032796 WHERE REQ_CONSECUTIVO=268784 AND DCM_RADICACION=4330999;
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='CONFIR_OK', RQHV_CEDULA=1032796 WHERE REQ_CONSECUTIVO=268784 AND DCM_RADICACION=4330999;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='DISPONIBLE', RQHV_CEDULA=208547 WHERE REQ_CONSECUTIVO=351376 AND DCM_RADICACION=3603892;
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='CONFIR_OK', RQHV_CEDULA=208547 WHERE REQ_CONSECUTIVO=351376 AND DCM_RADICACION=3603892;
/
commit;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET EPL_ND=1053585200 WHERE REQ_CONSECUTIVO=351376 AND DCM_RADICACION=4330818;--1113610--556332
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET EPL_ND=321837 WHERE REQ_CONSECUTIVO=268784 AND DCM_RADICACION=4330998;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET EPL_ND=324656 WHERE REQ_CONSECUTIVO=351376 AND DCM_RADICACION=4330753;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET EPL_ND=1032796 WHERE REQ_CONSECUTIVO=268784 AND DCM_RADICACION=4330999;
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET EPL_ND=208547 WHERE REQ_CONSECUTIVO=351376 AND DCM_RADICACION=3603892;

/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='APLICADO' WHERE REQ_CONSECUTIVO=343637 AND DCM_RADICACION=4223023;
/

/
--****************************************************************
--** CREATE OR REPLACE TRIGGER RHU.HV_CONTRATO_AUDIT
--** AFTER INSERT OR UPDATE ON RHU.CONTRATO
--****************************************************************
SELECT * FROM RHU.CONTRATO ORDER BY CTO_NUMERO DESC;
/
SELECT *
FROM RHU.CONTRATO
WHERE CTO_FECING BETWEEN SYSDATE - 7 AND SYSDATE
ORDER BY CTO_FECING DESC;
/
<<<<<<< HEAD
SELECT * FROM RHU.CONTRATO 
where EPL_ND=1072649998; --CTO_NUMERO=427463 
and EPL_ND=1072649998
=======
SELECT * FROM RHU.CONTRATO where CTO_NUMERO=427463 and EPL_ND=1072649998
>>>>>>> 881ac0ffe60537651b3bd138deb24aa2e246d04d
/
UPDATE RHU.CONTRATO set EPL_ND = 556332 WHERE CTO_NUMERO=427463 and EPL_ND=1072649998;
/
UPDATE RHU.CONTRATO set EPL_ND = 321837 WHERE CTO_NUMERO=1707494 and EPL_ND=525696325;
/
UPDATE RHU.CONTRATO set EPL_ND = 324656 WHERE CTO_NUMERO=1707495 and EPL_ND=524862354;
/
UPDATE RHU.CONTRATO set EPL_ND = 1032796 WHERE CTO_NUMERO=1707492 and EPL_ND=489623565;
/
UPDATE RHU.CONTRATO set EPL_ND = 208547 WHERE CTO_NUMERO=1707493 and EPL_ND=458962356;

/
ALTER TRIGGER RHU.DB_VALIDACION_CONTRATO ENABLE;
ALTER TRIGGER RHU.DB_VALIDACION_CONTRATO DISABLE;

/
SELECT * FROM RHU.CONTRATO WHERE CTO_NUMERO=427463;
SELECT NRO_REQUISICION FROM LIBROINGRESO WHERE CTO_NUMERO=424062;
SELECT * FROM RHU.Replication_Detail order by ID_RD desc;--9762
/
<<<<<<< HEAD
SELECT * FROM RHU.CONTRATO WHERE EPL_ND=13387660;
/
SELECT * FROM  RHU.CONTRATO ORDER BY CTO_NUMERO DESC;
/
SELECT * FROM REQUISICION_HOJA_VIDA WHERE EPL_ND IN (13387660,
1976299,
101908331396,
101908331397,
101908331398,
101908331399,
85962362,
85962374);
/
SELECT REQ_ESTADO FROM REQUISICION GROUP BY (REQ_ESTADO); 
SELECT REQ_ESTADO FROM REQUISICION WHERE REQ_CONSECUTIVO= 351382;
--UPDATE REQUISICION SET REQ_ESTADO ='EN_RECLUTAMIENTO' WHERE REQ_CONSECUTIVO= 351382;
/
SELECT * FROM EMPLEADO WHERE EPL_ND =13387660;
/
=======
>>>>>>> 881ac0ffe60537651b3bd138deb24aa2e246d04d
--*************************SIN LIB_INGRESO***************************************

UPDATE RHU.CONTRATO SET ECT_SIGLA='INA' WHERE EPL_ND=556332 AND CTO_NUMERO=427463;
/
<<<<<<< HEAD
UPDATE RHU.CONTRATO SET ECT_SIGLA='ACT' WHERE EPL_ND=13387660 AND CTO_NUMERO=1707534;
=======
UPDATE RHU.CONTRATO SET ECT_SIGLA='PRE' WHERE EPL_ND=556332 AND CTO_NUMERO=427463;
>>>>>>> 881ac0ffe60537651b3bd138deb24aa2e246d04d
/
/
--****************************CON LIB_INGRESO************************************

UPDATE RHU.CONTRATO SET ECT_SIGLA='INA' WHERE EPL_ND=321837 AND CTO_NUMERO=1707494;
/
UPDATE RHU.CONTRATO SET ECT_SIGLA='PRE' WHERE EPL_ND=321837 AND CTO_NUMERO=1707494;
/
/

UPDATE RHU.CONTRATO SET ECT_SIGLA='INA' WHERE EPL_ND=324656 AND CTO_NUMERO=1707495;
/
UPDATE RHU.CONTRATO SET ECT_SIGLA='PRE' WHERE EPL_ND=324656 AND CTO_NUMERO=1707495;
/
/

UPDATE RHU.CONTRATO SET ECT_SIGLA='INA' WHERE EPL_ND=1032796 AND CTO_NUMERO=1707492;
/
UPDATE RHU.CONTRATO SET ECT_SIGLA='PRE' WHERE EPL_ND=1032796 AND CTO_NUMERO=1707492;
/
/

UPDATE RHU.CONTRATO SET ECT_SIGLA='INA' WHERE EPL_ND=208547 AND CTO_NUMERO=1707493;
/
UPDATE RHU.CONTRATO SET ECT_SIGLA='PRE' WHERE EPL_ND=208547 AND CTO_NUMERO=1707493;
/
/
--****************************************************************
--** CREATE OR REPLACE TRIGGER PAR.REQ_OKVAL_DOCS_REPLICATE
--** AFTER INSERT OR UPDATE ON PAR.REQUISICION_HOJA_VIDA
--****************************************************************
SELECT * FROM RHU.OBSERVACION_LINGRESO ORDER BY LIB_CONSECUTIVO DESC;
/
SELECT *
FROM PAR.REQUISICION_HOJA_VIDA
WHERE RQHV_FECHA BETWEEN SYSDATE - 7 AND SYSDATE
ORDER BY RQHV_FECHA DESC;
/
SELECT * FROM RHU.REQUIRED_DOCUMENTS;
/
SELECT *
FROM perfil_estado_lingreso pel, perfil_detalle_lingreso pdl
WHERE pel.pre_codigo = pdl.pre_codigo
AND pel.lib_estado = pdl.lib_estado
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='DISPONIBLE' WHERE REQ_CONSECUTIVO=343637 AND DCM_RADICACION=4223123;--PT 8888888
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='CONFIR_OK' WHERE REQ_CONSECUTIVO=343637 AND DCM_RADICACION=4223123;--PT 8888888
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='ASISTIO' WHERE REQ_CONSECUTIVO=343637 AND DCM_RADICACION=4223123;--PT 8888888
/
UPDATE PAR.REQUISICION_HOJA_VIDA SET STDO_ESTADO='OK_VALIDADO' WHERE REQ_CONSECUTIVO=343637 AND DCM_RADICACION=4223123;--PT 8888888
/
--****************************************************************
--** CREATE OR REPLACE TRIGGER RHU.HV_EMPLEADO_REPL
--** AFTER INSERT OR UPDATE ON RHU.EMPLEADO
--****************************************************************
/
--****************************************************************
--** CREATE OR REPLACE TRIGGER RHU.HV_EMPLEADO_MASV
--** AFTER INSERT OR UPDATE ON RHU.EMPLEADO
--****************************************************************
/
SELECT * FROM EMPLEADO  ORDER BY AUD_FECHA DESC;
/
SELECT *
FROM EMPLEADO
WHERE AUD_FECHA BETWEEN SYSDATE - 7 AND SYSDATE
ORDER BY AUD_FECHA DESC;
/
UPDATE EMPLEADO SET FUENTE='CONTRATO' WHERE EPL_ND=485696323 AND TDC_TD='CC';
/
UPDATE EMPLEADO SET FUENTE='COMPUTRABAJO_MASIVO' WHERE EPL_ND=485696323 AND TDC_TD='CC';

/
SELECT * FROM RHU.Replication_Config WHERE LOCAL_TABLE_REF = 'RHU.EMPLEADO' AND GCP_TABLE_REF = 'BasicData'
