GRANT ALL ON RHU.QB_DATA_REPLICATION TO PUBLIC;

CREATE PUBLIC SYNONYM QB_DATA_REPLICATION FOR RHU.QB_DATA_REPLICATION;

INSERT INTO ZONA (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, ZON_CODIGO, ZON_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 20, 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'BETANIA', 'S');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'NAZARETH', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'EL RAIZAL', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'ISTMO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAGUNA VERDE', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS PALMAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS SOPAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS ÁNIMAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS AURAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LOS RÍOS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'PEÑALISA', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SANTA ROSA ALTA', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SANTA ROSA BAJA', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'TABACO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'TAQUECITOS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LA UNIÓN', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'NUEVA GRANADA', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SAN JUAN DE SUMAPAZ', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'CAPITOLIO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'CHORRERAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'CONCEPCIÓN', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'EL TOLDO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAGUNITAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS VEGAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SAN ANTONIO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SAN JOSÉ', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SAN JUAN', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SANTO DOMINGO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'TUNAL ALTO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'TUNAL BAJO', 'N');

ALTER TABLE rhu.tsel_emp_dat MODIFY (RAZA VARCHAR2(4000 BYTE));

INSERT INTO USUARIOS_DOMINIO (UDS_ID, ROD_ID, USU_USUARIO, UDS_ESTADO, AUD_FECHA, AUD_USUARIO)
SELECT (SELECT MAX(UDS_ID) FROM USUARIOS_DOMINIO) + ROWNUM, 
       ROD_ID, 
       'DESIERRA', 
       'S', 
       SYSDATE, 
       'JUFORERO'
FROM (
    SELECT DISTINCT ROD_ID FROM ( 
        SELECT 5 AS ROD_ID FROM DUAL UNION ALL
        SELECT 9 FROM DUAL UNION ALL
        SELECT 10 FROM DUAL UNION ALL
        SELECT 12 FROM DUAL UNION ALL
        SELECT 15 FROM DUAL UNION ALL
        SELECT 16 FROM DUAL UNION ALL
        SELECT 25 FROM DUAL UNION ALL
        SELECT 27 FROM DUAL UNION ALL
        SELECT 32 FROM DUAL UNION ALL
        SELECT 38 FROM DUAL UNION ALL
        SELECT 47 FROM DUAL UNION ALL
        SELECT 50 FROM DUAL UNION ALL
        SELECT 74 FROM DUAL UNION ALL
        SELECT 81 FROM DUAL UNION ALL
        SELECT 105 FROM DUAL
    )
);
INSERT INTO USUARIOS_DOMINIO (UDS_ID, ROD_ID, USU_USUARIO, UDS_ESTADO, AUD_FECHA, AUD_USUARIO)
SELECT (SELECT MAX(UDS_ID) FROM USUARIOS_DOMINIO) + ROWNUM, 
       ROD_ID, 
       'JUFORERO', 
       'S', 
       SYSDATE, 
       'DESIERRA'
FROM (SELECT 5 AS ROD_ID FROM DUAL UNION ALL
      SELECT 9 FROM DUAL UNION ALL
      SELECT 10 FROM DUAL UNION ALL
      SELECT 12 FROM DUAL UNION ALL
      SELECT 15 FROM DUAL UNION ALL
      SELECT 16 FROM DUAL UNION ALL
      SELECT 25 FROM DUAL UNION ALL
      SELECT 27 FROM DUAL UNION ALL
      SELECT 27 FROM DUAL UNION ALL
      SELECT 32 FROM DUAL UNION ALL
      SELECT 38 FROM DUAL UNION ALL
      SELECT 47 FROM DUAL UNION ALL
      SELECT 50 FROM DUAL UNION ALL
      SELECT 74 FROM DUAL UNION ALL
      SELECT 76 FROM DUAL UNION ALL
      SELECT 81 FROM DUAL UNION ALL
      SELECT 105 FROM DUAL);



commit;