/
GRANT ALL ON RHU.QB_DATA_REPLICATION TO PUBLIC;
GRANT ALL ON FB_LIMPIAR_CADENA_NUE TO PUBLIC;
GRANT ALL ON tsel_entrevista_datfijo TO PUBLIC;
GRANT ALL ON empleado TO PUBLIC;
GRANT ALL ON tsel_experiencia_laboral TO PUBLIC;
GRANT ALL ON tsel_nivel_educativo TO PUBLIC;
GRANT ALL ON usuarios TO PUBLIC;
GRANT ALL ON TSEL_EMPLEADO_APTITUD TO PUBLIC;
GRANT ALL ON TSEL_NUCLEO_FAMILIAR TO PUBLIC;
/
Insert into ROLES_DOMINIO (ROD_ID,DSA_ID,ROD_NOMBRE,ROD_DEFAULT,ROD_ESTADO,ROD_CONFIGURADO,ROD_PUBLICO,AUD_FECHA,AUD_USUARIO) 
values ((select MAX(ROD_ID)+1 from ROLES_DOMINIO),5,'SELROL ADMIN OFERTAS RECLUTADOR','N','N','N','N',SYSDATE,'DESIERRA');

Insert into USUARIOS_DOMINIO (UDS_ID,ROD_ID,USU_USUARIO,UDS_ESTADO,AUD_FECHA,AUD_USUARIO) 
values ((select MAX(UDS_ID)+1 from usuarios_dominio),140,'YMONDRAGON','S',SYSDATE,'DESIERRA');

Insert into USUARIOS_DOMINIO (UDS_ID,ROD_ID,USU_USUARIO,UDS_ESTADO,AUD_FECHA,AUD_USUARIO) 
values ((select MAX(UDS_ID)+1 from usuarios_dominio),140,'MREY','S',SYSDATE,'DESIERRA');

Insert into USUARIOS_DOMINIO (UDS_ID,ROD_ID,USU_USUARIO,UDS_ESTADO,AUD_FECHA,AUD_USUARIO) 
values ((select MAX(UDS_ID)+1 from usuarios_dominio),140,'LODUARTE','S',SYSDATE,'DESIERRA');
/
INSERT into tsel_tipo_documento (TDO_ID_TIPO_DOCUMENTO, TDO_NOMBRE, TDO_ABREVIATURA, AUD_USER, AUD_FECHA) 
values (15, 'PERMISO TEMPORAL', 'PT', 'JULFORERO', SYSDATE);
/
INSERT into tsel_tipo_documento (TDO_ID_TIPO_DOCUMENTO, TDO_NOMBRE, TDO_ABREVIATURA, AUD_USER, AUD_FECHA) 
values (16, 'CARNET DIPLOMATICO ', 'CD', 'JULFORERO', SYSDATE);
/
INSERT INTO ADM.TIPO_DOCUMENTO (TPD_CODIGO, TPD_DESCRIPCION, DTD_CODIGO, AUD_FECHA, AUD_USUARIO, TPD_ALIAS, TPD_GRUPO)
VALUES (123, 'Diploma Técnica Laboral', NULL, SYSDATE, 'JULFORERO', 'RECLUTADOR', NULL);

INSERT INTO ADM.TIPO_DOCUMENTO (TPD_CODIGO, TPD_DESCRIPCION, DTD_CODIGO, AUD_FECHA, AUD_USUARIO, TPD_ALIAS, TPD_GRUPO)
VALUES (124, 'Diploma Preescolar', NULL, SYSDATE, 'JULFORERO', 'RECLUTADOR', NULL);

INSERT INTO ADM.TIPO_DOCUMENTO (TPD_CODIGO, TPD_DESCRIPCION, DTD_CODIGO, AUD_FECHA, AUD_USUARIO, TPD_ALIAS, TPD_GRUPO)
VALUES (125, 'Diploma Educación Formal - Otros', NULL, SYSDATE, 'JULFORERO', 'RECLUTADOR', NULL);

INSERT INTO ADM.TIPO_DOCUMENTO (TPD_CODIGO, TPD_DESCRIPCION, DTD_CODIGO, AUD_FECHA, AUD_USUARIO, TPD_ALIAS, TPD_GRUPO)
VALUES (128, 'HOJA DE VIDA GENERADA DEL RECLUTADOR', NULL, SYSDATE, 'JULFORERO', 'RECLUTADOR', NULL);

--INSERT INTO ADM.TIPO_DOCUMENTO (TPD_CODIGO, TPD_DESCRIPCION, DTD_CODIGO, AUD_FECHA, AUD_USUARIO, TPD_ALIAS, TPD_GRUPO)
--VALUES (127, 'Certificado Laboral', NULL, SYSDATE, 'JULFORERO', 'RECLUTADOR', NULL);

INSERT INTO ADM.TIPO_DOCUMENTO (TPD_CODIGO, TPD_DESCRIPCION, DTD_CODIGO, AUD_FECHA, AUD_USUARIO, TPD_ALIAS, TPD_GRUPO)
VALUES (126, 'Nuevos Archivos', NULL, SYSDATE, 'JULFORERO', 'RECLUTADOR', NULL);

INSERT INTO ZONA (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, ZON_CODIGO, ZON_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 20, 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'BETANIA', 'S');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'NAZARETH', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'EL RAIZAL', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'ISTMO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAGUNA VERDE', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS PALMAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS SOPAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS ÁNIMAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS AURAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LOS RÍOS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'PEÑALISA', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SANTA ROSA ALTA', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SANTA ROSA BAJA', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'TABACO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'TAQUECITOS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LA UNIÓN', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'NUEVA GRANADA', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SAN JUAN DE SUMAPAZ', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'CAPITOLIO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'CHORRERAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'CONCEPCIÓN', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'EL TOLDO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAGUNITAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'LAS VEGAS', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SAN ANTONIO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SAN JOSÉ', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SAN JUAN', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'SANTO DOMINGO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'TUNAL ALTO', 'N');

INSERT INTO BARRIO (PAI_NOMBRE, DPT_NOMBRE, CIU_NOMBRE, ZON_NOMBRE, BAR_NOMBRE, BAR_DEFECTO) VALUES ('COLOMBIA', 'CUNDINAMARCA', 'SANTAFE DE BOGOTA', 'SUMAPAZ', 'TUNAL BAJO', 'N');

commit;
/
ALTER TRIGGER RHU.DB_VALIDA_NOMBRES DISABLE;
/
ALTER TRIGGER RHU.DB_LIMPIAR_NOMBRES DISABLE;
/
ALTER TABLE rhu.tsel_emp_dat MODIFY (RAZA VARCHAR2(4000 BYTE));
/
INSERT INTO adm.propiedades_documento (
    PRD_CODIGO, 
    TPD_CODIGO, 
    TDT_ORIGEN, 
    TDT_OBLIGATORIO, 
    TDT_VERSION, 
    TDT_VISIBLE, 
    TDT_CATEGORIA, 
    AUD_FECHA, 
    AUD_USUARIO
) VALUES (
    129, 
    129, --HOJA DE VIDA GENERADA DEL RECLUTADOR (reclutador)
    'O', 
    'O', 
    'V', 
    NULL, 
    NULL, 
    TO_DATE('18/12/24', 'DD/MM/YY'), 
    'JULFORERO'
);
/
INSERT INTO adm.propiedades_documento (
    PRD_CODIGO, 
    TPD_CODIGO, 
    TDT_ORIGEN, 
    TDT_OBLIGATORIO, 
    TDT_VERSION, 
    TDT_VISIBLE, 
    TDT_CATEGORIA, 
    AUD_FECHA, 
    AUD_USUARIO
) VALUES (
    123, 
    123, --Diploma Técnica Laboral
    'O', 
    'O', 
    'S', 
    NULL, 
    NULL, 
    TO_DATE('18/12/24', 'DD/MM/YY'), 
    'JULFORERO'
);
/
INSERT INTO adm.propiedades_documento (
    PRD_CODIGO, 
    TPD_CODIGO, 
    TDT_ORIGEN, 
    TDT_OBLIGATORIO, 
    TDT_VERSION, 
    TDT_VISIBLE, 
    TDT_CATEGORIA, 
    AUD_FECHA, 
    AUD_USUARIO
) VALUES (
    124, 
    124, --Diploma Preescolar
    'O', 
    'O', 
    'V', 
    NULL, 
    NULL, 
    TO_DATE('18/12/24', 'DD/MM/YY'), 
    'JULFORERO'
);
/
INSERT INTO adm.propiedades_documento (
    PRD_CODIGO, 
    TPD_CODIGO, 
    TDT_ORIGEN, 
    TDT_OBLIGATORIO, 
    TDT_VERSION, 
    TDT_VISIBLE, 
    TDT_CATEGORIA, 
    AUD_FECHA, 
    AUD_USUARIO
) VALUES (
    125, 
    125, --Diploma Educación Formal - Otros
    'O', 
    'O', 
    'S', 
    NULL, 
    NULL, 
    TO_DATE('18/12/24', 'DD/MM/YY'), 
    'JULFORERO'
);
/
INSERT INTO adm.propiedades_documento (
    PRD_CODIGO, 
    TPD_CODIGO, 
    TDT_ORIGEN, 
    TDT_OBLIGATORIO, 
    TDT_VERSION, 
    TDT_VISIBLE, 
    TDT_CATEGORIA, 
    AUD_FECHA, 
    AUD_USUARIO
) VALUES (
    126, 
    126, --Nuevos Archivos
    'O', 
    'O', 
    'S', 
    NULL, 
    NULL, 
    TO_DATE('18/12/24', 'DD/MM/YY'), 
    'JULFORERO'
);
/
INSERT INTO adm.propiedades_documento (
    PRD_CODIGO, 
    TPD_CODIGO, 
    TDT_ORIGEN, 
    TDT_OBLIGATORIO, 
    TDT_VERSION, 
    TDT_VISIBLE, 
    TDT_CATEGORIA, 
    AUD_FECHA, 
    AUD_USUARIO
) VALUES (
    128, 
    128, --CERTIFICADOS DE IDIOMAS
    'O', 
    'O', 
    'S', 
    NULL, 
    NULL, 
    TO_DATE('18/12/24', 'DD/MM/YY'), 
    'JULFORERO'
);
/
/
UPDATE adm.propiedades_documento
SET 
    PRD_CODIGO = 127    
WHERE TPD_CODIGO = 127;
/
UPDATE adm.propiedades_documento
SET 
    PRD_CODIGO = 130    
WHERE TPD_CODIGO = 130;
/
CREATE OR REPLACE TRIGGER RHU.DB_INSERTA_BARRIO
BEFORE INSERT OR UPDATE ON RHU.EMPLEADO
REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
-- ******************************************************************
-- ** SCRIPT  : DRHU0196.SQL
-- ** DIRECTORIO : C:\FTES\V1\SQL
-- ** OBJETIVO  : Creacion Paquete db_inserta_barrio
-- ** ESQUEMA  : RHU
-- ** CREACION  : Hugo Quintero Bertel
-- ** ACTUALIZACION : 2014/03/04
-- ******************************************************************
DECLARE
  v_count NUMBER := 0; -- Variable para contar si el registro ya existe
  vcError VARCHAR2(2000);
BEGIN
  -- Verificar si el registro ya existe en la tabla BARRIO
  SELECT COUNT(*)
  INTO v_count
  FROM BARRIO
  WHERE UPPER(PAI_NOMBRE) = UPPER(:NEW.PAI_NOMBRE_RES)
    AND UPPER(DPT_NOMBRE) = UPPER(:NEW.DPT_NOMBRE_RES)
    AND UPPER(CIU_NOMBRE) = UPPER(:NEW.CIU_NOMBRE_RES)
    AND UPPER(ZON_NOMBRE) = UPPER(:NEW.ZON_NOMBRE)
    AND UPPER(BAR_NOMBRE) = UPPER(:NEW.BAR_NOMBRE);

  -- Solo insertar si el registro no existe
  IF v_count = 0 THEN
    INSERT INTO BARRIO
    (
      PAI_NOMBRE,
      DPT_NOMBRE,
      CIU_NOMBRE,
      ZON_NOMBRE,
      BAR_NOMBRE,
      BAR_DEFECTO
    )
    VALUES
    (
      :NEW.PAI_NOMBRE_RES,
      :NEW.DPT_NOMBRE_RES,
      :NEW.CIU_NOMBRE_RES,
      :NEW.ZON_NOMBRE,
      :NEW.BAR_NOMBRE,
      'N'
    );
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    vcError := 'Error en el Trigger RHU.DB_INSERTA_BARRIO: ' || SQLERRM;
    -- Opcional: Puedes registrar el error en una tabla de auditoría
    NULL; -- Ignorar el error
END;

